#include <iostream>
#include <iomanip>
#include <string>
#include <algorithm>
#include <vector>
#include <limits>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <cmath>
#include <sstream>
#include <stdexcept> 
using std::cout;
using std::cin;
using std::right;
using std::left;
using std::setprecision;
using std::string;
using std::setw;
using std::endl;
using std::copy;
using std::fixed;
using std::swap;
using std::vector;
using std::sort;
using std::begin;
using std::end;
using std::numeric_limits;
using std::streamsize;
using std::ifstream;
using std::stringstream;

